# Generated by Django 6.0.4 on 2026-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_created_at_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(
                default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_factory_at',
            field=models.DateTimeField(
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(
                blank=True,
                null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending',
                     'Pending'),
                    ('sent_to_factory',
                     'Sent to Factory'),
                    ('shipped',
                     'Shipped'),
                    ('delivered',
                     'Delivered')],
                default='pending',
                max_length=20),
        ),
    ]
